/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Antonella
 */
public class Menu_principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_principal
     */
    public Menu_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        Fondo = new Fondo();
        jPanel1 = new Fondo();
        aggciudad = new javax.swing.JButton();
        aggciudad1 = new javax.swing.JButton();
        aggciudad2 = new javax.swing.JButton();
        aggciudad3 = new javax.swing.JButton();
        aggciudad4 = new javax.swing.JButton();

        jButton7.setText("Guardar Grafo");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(204, 255, 204));
        jButton10.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(51, 51, 51));
        jButton10.setText("Eliminar Ciudad");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        aggciudad.setBackground(new java.awt.Color(22, 19, 15));
        aggciudad.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        aggciudad.setForeground(new java.awt.Color(132, 107, 82));
        aggciudad.setText("Nueva Simulacion");
        aggciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggciudadActionPerformed(evt);
            }
        });
        Fondo.add(aggciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 370, 39));

        aggciudad1.setBackground(new java.awt.Color(22, 19, 15));
        aggciudad1.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        aggciudad1.setForeground(new java.awt.Color(102, 102, 102));
        aggciudad1.setText("Eliminar Ciudad");
        aggciudad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggciudad1ActionPerformed(evt);
            }
        });
        Fondo.add(aggciudad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 180, 39));

        aggciudad2.setBackground(new java.awt.Color(22, 19, 15));
        aggciudad2.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        aggciudad2.setForeground(new java.awt.Color(102, 102, 102));
        aggciudad2.setText("Guardar Grafo");
        aggciudad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggciudad2ActionPerformed(evt);
            }
        });
        Fondo.add(aggciudad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 180, 39));

        aggciudad3.setBackground(new java.awt.Color(22, 19, 15));
        aggciudad3.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        aggciudad3.setForeground(new java.awt.Color(102, 102, 102));
        aggciudad3.setText("Agregar ciudad");
        aggciudad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggciudad3ActionPerformed(evt);
            }
        });
        Fondo.add(aggciudad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 180, 39));

        aggciudad4.setBackground(new java.awt.Color(22, 19, 15));
        aggciudad4.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        aggciudad4.setForeground(new java.awt.Color(102, 102, 102));
        aggciudad4.setText("Cargar Grafo");
        aggciudad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggciudad4ActionPerformed(evt);
            }
        });
        Fondo.add(aggciudad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 180, 39));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void aggciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aggciudadActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void aggciudad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggciudad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aggciudad1ActionPerformed

    private void aggciudad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggciudad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aggciudad2ActionPerformed

    private void aggciudad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggciudad3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aggciudad3ActionPerformed

    private void aggciudad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggciudad4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aggciudad4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton aggciudad;
    private javax.swing.JButton aggciudad1;
    private javax.swing.JButton aggciudad2;
    private javax.swing.JButton aggciudad3;
    private javax.swing.JButton aggciudad4;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

  class Fondo extends JPanel{
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen= new ImageIcon(getClass().getResource("/Imagenes/menuprinc.jpg")).getImage();
            g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
                    setOpaque(false);
                    
                    super.paint(g);
        }
    }}


