/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Antonella
 */
public class Menu_principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_principal
     */
    public Menu_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        Fondo = new Fondo();
        jPanel1 = new Fondo();
        cargargrafo = new javax.swing.JButton();
        Nuevasimulacion = new javax.swing.JButton();
        aggciudad = new javax.swing.JButton();
        savegrafo = new javax.swing.JButton();
        eliminarciudad = new javax.swing.JButton();

        jButton7.setText("Guardar Grafo");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(204, 255, 204));
        jButton10.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(51, 51, 51));
        jButton10.setText("Eliminar Ciudad");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        cargargrafo.setBackground(new java.awt.Color(102, 51, 0));
        cargargrafo.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        cargargrafo.setForeground(new java.awt.Color(51, 51, 51));
        cargargrafo.setText("Cargar Grafo");
        cargargrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargargrafoActionPerformed(evt);
            }
        });
        Fondo.add(cargargrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 180, 39));

        Nuevasimulacion.setBackground(new java.awt.Color(102, 51, 0));
        Nuevasimulacion.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        Nuevasimulacion.setForeground(new java.awt.Color(51, 51, 51));
        Nuevasimulacion.setText("Nueva Simulacion");
        Fondo.add(Nuevasimulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 380, 40));

        aggciudad.setBackground(new java.awt.Color(102, 51, 0));
        aggciudad.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        aggciudad.setForeground(new java.awt.Color(51, 51, 51));
        aggciudad.setText("Agregar ciudad");
        aggciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggciudadActionPerformed(evt);
            }
        });
        Fondo.add(aggciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 180, 39));

        savegrafo.setBackground(new java.awt.Color(102, 51, 0));
        savegrafo.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        savegrafo.setForeground(new java.awt.Color(51, 51, 51));
        savegrafo.setText("Guardar Grafo");
        savegrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savegrafoActionPerformed(evt);
            }
        });
        Fondo.add(savegrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 180, 39));

        eliminarciudad.setBackground(new java.awt.Color(102, 51, 0));
        eliminarciudad.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        eliminarciudad.setForeground(new java.awt.Color(51, 51, 51));
        eliminarciudad.setText("Eliminar Ciudad");
        eliminarciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarciudadActionPerformed(evt);
            }
        });
        Fondo.add(eliminarciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 180, 39));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cargargrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargargrafoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargargrafoActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void aggciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aggciudadActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void savegrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savegrafoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savegrafoActionPerformed

    private void eliminarciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarciudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton Nuevasimulacion;
    private javax.swing.JButton aggciudad;
    private javax.swing.JButton cargargrafo;
    private javax.swing.JButton eliminarciudad;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton savegrafo;
    // End of variables declaration//GEN-END:variables

  class Fondo extends JPanel{
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen= new ImageIcon(getClass().getResource("/Imagenes/menuprinc.jpg")).getImage();
            g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
                    setOpaque(false);
                    
                    super.paint(g);
        }
    }}


